 const firstImageData = [
    {
      no: 1,
      item_en: "POP Work",
      item_mr: "पीओपी काम",
      checking_points_en: ["Done"],
      checking_points_mr: ["पूर्ण"],
      isSubItem: false,
    },
    {
      no: 2,
      item_en: "PVC Sheet",
      item_mr: "पीवीसी शीट",
      checking_points_en: ["POP sheet work finishing"],
      checking_points_mr: ["पीओपी शीट काम पूर्णत्वास"],
      isSubItem: false,
    },
    {
      no: 3,
      item_en: "Checking Points",
      item_mr: "तपासणी बिंदू",
      checking_points_en: ["Light cut-out"],
      checking_points_mr: ["लाईट कटिंग"],
      isSubItem: false,
    },
    {
      no: "",
      item_en: "",
      item_mr: "",
      checking_points_en: ["POP Work Level"],
      checking_points_mr: ["पीओपी काम स्तर"],
      isSubItem: true,
    },
    {
      no: "",
      item_en: "",
      item_mr: "",
      checking_points_en: ["Border Patti"],
      checking_points_mr: ["बॉर्डर पट्टी"],
      isSubItem: true,
    },
    {
      no: 4,
      item_en: "Gypsum Sheet",
      item_mr: "जिप्सम शीट",
      checking_points_en: ["POP sheet work finishing"],
      checking_points_mr: ["पीओपी शीट काम पूर्णत्वास"],
      isSubItem: false,
    },
    {
      no: "",
      item_en: "",
      item_mr: "",
      checking_points_en: ["Light cut-out"],
      checking_points_mr: ["लाईट कटिंग"],
      isSubItem: true,
    },
    {
      no: "",
      item_en: "",
      item_mr: "",
      checking_points_en: ["Sheet joint work"],
      checking_points_mr: ["शीट जोड काम"],
      isSubItem: true,
    },
    {
      no: "",
      item_en: "",
      item_mr: "",
      checking_points_en: ["Putty coating double"],
      checking_points_mr: ["पुटी कोटिंग डबल"],
      isSubItem: true,
    },
    {
      no: "",
      item_en: "",
      item_mr: "",
      checking_points_en: ["Proper color work"],
      checking_points_mr: ["योग्य रंग काम"],
      isSubItem: true,
    },
  ];

  // Data for the second image (Flooring and Tiles Checklist)
  const secondImageData = [
    {
      no: 1,
      item_en: "Flooring Tiles Work",
      item_mr: "फ्लोअरिंग टाइल्स काम",
      checking_points_en: ["Finishing work"],
      checking_points_mr: ["समाप्ती काम"],
      isSubItem: false,
    },
    {
      no: "",
      item_en: "",
      item_mr: "",
      checking_points_en: ["Level work"],
      checking_points_mr: ["स्तर काम"],
      isSubItem: true,
    },
    {
      no: "",
      item_en: "",
      item_mr: "",
      checking_points_en: ["White cement filling"],
      checking_points_mr: ["पांढरे सिमेंट भरणे"],
      isSubItem: true,
    },
    {
      no: "",
      item_en: "",
      item_mr: "",
      checking_points_en: ["Water level drain point"],
      checking_points_mr: ["पाण्याचा स्तर निचरा बिंदू"],
      isSubItem: true,
    },
    {
      no: "",
      item_en: "",
      item_mr: "",
      checking_points_en: ["Floor sound check"],
      checking_points_mr: ["मजल्याचा आवाज तपासणी"],
      isSubItem: true,
    },
    {
      no: "",
      item_en: "",
      item_mr: "",
      checking_points_en: ["All tiles + point check"],
      checking_points_mr: ["सर्व टाइल्स + बिंदू तपासणी"],
      isSubItem: true,
    },
    {
      no: 2,
      item_en: "Marble Work",
      item_mr: "मार्बल काम",
      checking_points_en: ["Granite patta work"],
      checking_points_mr: ["ग्रॅनाइट पट्टा काम"],
      isSubItem: false,
    },
    {
      no: 3,
      item_en: "Wall Tiles",
      item_mr: "भिंतीच्या टाइल्स",
      checking_points_en: ["Finishing work"],
      checking_points_mr: ["समाप्ती काम"],
      isSubItem: false,
    },
    {
      no: "",
      item_en: "",
      item_mr: "",
      checking_points_en: ["Level work"],
      checking_points_mr: ["स्तर काम"],
      isSubItem: true,
    },
    {
      no: "",
      item_en: "",
      item_mr: "",
      checking_points_en: ["White cement filling"],
      checking_points_mr: ["पांढरे सिमेंट भरणे"],
      isSubItem: true,
    },
    {
      no: "",
      item_en: "",
      item_mr: "",
      checking_points_en: ["Vertical and horizontal work check"],
      checking_points_mr: ["उभ्या आणि आडव्या कामाची तपासणी"],
      isSubItem: true,
    },
    {
      no: "",
      item_en: "",
      item_mr: "",
      checking_points_en: ["Wall tiles sound check"],
      checking_points_mr: ["भिंतीच्या टाइल्सचा आवाज तपासणी"],
      isSubItem: true,
    },
    {
      no: "",
      item_en: "",
      item_mr: "",
      checking_points_en: ["All tiles + point check"],
      checking_points_mr: ["सर्व टाइल्स + बिंदू तपासणी"],
      isSubItem: true,
    },
    {
      no: "",
      item_en: "",
      item_mr: "",
      checking_points_en: ["Wall tiles height check"],
      checking_points_mr: ["भिंतीच्या टाइल्सची उंची तपासणी"],
      isSubItem: true,
    },
  ];

  // Data for the third image (Owner Civil Work)
  const thirdImageData = [
    {
      no: 1,
      item_en: "CCTV 4 DVR - CP PLUS 2MP",
      item_mr: "सीसीटीव्ही 4 डीव्हीआर - सीपी प्लस 2 मेगापिक्सेल",
      checking_points_en: ["CAMERA + HDD DISK + DVR"],
      checking_points_mr: ["कॅमेरा + एचडीडी डिस्क + डीव्हीआर"],
    },
    {
      no: 2,
      item_en: "INTERNET",
      item_mr: "इंटरनेट",
      checking_points_en: ["12-Month plan 25 Mbps unlimited"],
      checking_points_mr: ["12 महिन्यांची योजना 25 एमबीपीएस अमर्यादित"],
    },
    {
      no: 3,
      item_en: "SPEAKER + AMPLIFIER",
      item_mr: "स्पीकर + एम्प्लिफायर",
      checking_points_en: ["Shutter + CEILING"],
      checking_points_mr: ["शटर + छत"],
    },
    {
      no: 4,
      item_en: "Oil Paint Asian",
      item_mr: "तेल पेंट एशियन",
      checking_points_en: [],
      checking_points_mr: [],
    },
    {
      no: 5,
      item_en: "Paint Luster Asian",
      item_mr: "पेंट लस्टर एशियन",
      checking_points_en: [],
      checking_points_mr: [],
    },
    {
      no: 6,
      item_en: "Shutter Logo",
      item_mr: "शटर लोगो",
      checking_points_en: ["Shutter"],
      checking_points_mr: ["शटर"],
    },
    {
      no: 7,
      item_en: "PLUMBER Labor",
      item_mr: "प्लंबर मजूर",
      checking_points_en: [],
      checking_points_mr: [],
    },
    {
      no: 8,
      item_en: "Water Tank - 1k Liter",
      item_mr: "पाण्याची टाकी - 1k लिटर",
      checking_points_en: ["1000ltr"],
      checking_points_mr: ["1000 लिटर"],
    },
    {
      no: 9,
      item_en: "HARDWARE MATERIAL (PIPE FITTING)",
      item_mr: "हार्डवेअर मटेरियल (पाइप फिटिंग)",
      checking_points_en: [],
      checking_points_mr: [],
    },
    {
      no: 10,
      item_en: "ELECTRICAL (POLYCAB)",
      item_mr: "इलेक्ट्रिकल (पॉलीकॅब)",
      checking_points_en: [],
      checking_points_mr: [],
    },
    {
      no: 11,
      item_en: "Crompton Fan",
      item_mr: "कॉम्पटन फॅन",
      checking_points_en: ["Kitchen"],
      checking_points_mr: ["स्वयंपाकघर"],
    },
    {
      no: 12,
      item_en: "Exhaust Fan",
      item_mr: "एक्झॉस्ट फॅन",
      checking_points_en: ['14" fan + Ducting'],
      checking_points_mr: ['14" फॅन + डक्टिंग'],
    },
    {
      no: 13,
      item_en: "22W D-line",
      item_mr: "22W डी-लाइन",
      checking_points_en: [],
      checking_points_mr: [],
    },
    {
      no: 14,
      item_en: "15W D-line",
      item_mr: "15W डी-लाइन",
      checking_points_en: [],
      checking_points_mr: [],
    },
    {
      no: 15,
      item_en: "10W D-line",
      item_mr: "10W डी-लाइन",
      checking_points_en: [],
      checking_points_mr: [],
    },
    {
      no: 16,
      item_en: "Shop Cleaning",
      item_mr: "दुकान साफसफाई",
      checking_points_en: [],
      checking_points_mr: [],
    },
    {
      no: 17,
      item_en: "GAS PIPING",
      item_mr: "गॅस पाइपिंग",
      checking_points_en: [],
      checking_points_mr: [],
    },
    {
      no: 18,
      item_en: "GRANITE PATTA",
      item_mr: "ग्रॅनाइट पट्टा",
      checking_points_en: ["Shutter Patta"],
      checking_points_mr: ["शटर पट्टा"],
    },
    {
      no: 19,
      item_en: "PLASTER + RABBIT",
      item_mr: "प्लास्टर + रॅबिट",
      checking_points_en: ["PLASTER SHOP WALL"],
      checking_points_mr: ["प्लास्टर शॉप वॉल"],
    },
  ];

  const config = {
    en: {
      titleFirst: "Inspection Checklist",
      titleSecond: "Flooring and Tiles Checklist",
      titleThird: "Owner Civil Work",
      branchName: "Branch Name: A.B. Road, Indore",
      ownerName: "Owner Name: Mr. Raj Anil Sisodiya",
      dateLabel: "Date: 3/21/2024",
      mobileLabel: "Mobile Number: 9131312816",
      tableHeaders: [
        "No",
        "Item",
        "Checking Points",
        "Done",
        "Pending",
        "Not Applicable",
      ],
      backButton: "Back",
      nextButton: "Next",
      submitButton: "Submit",
      popupMessage: "Submitted Successfully",
      validationMessage:
        "Please ensure all items in the current checklist are marked.",
    },
    mr: {
      titleFirst: "तपासणी चेकलिस्ट",
      titleSecond: "फ्लोअरिंग आणि टाइल्स चेकलिस्ट",
      titleThird: "मालक सिव्हिल वर्क",
      branchName: "शाखेचे नाव: ए.बी. रोड, इंदूर",
      ownerName: "मालकाचे नाव: श्री. राज अनिल सिसोदिया",
      dateLabel: "तारीख: ३/२१/२०२४",
      mobileLabel: "मोबाइल नंबर: ९१३१३१२८१६",
      tableHeaders: [
        "अनु. क्र.",
        "आयटम",
        "तपासणी बिंदू",
        "पूर्ण",
        "प्रलंबित",
        "लागू नाही",
      ],
      backButton: "मागे",
      nextButton: "पुढे",
      submitButton: "सबमिट",
      popupMessage: "यशस्वीरित्या सबमिट केले",
      validationMessage:
        "कृपया खात्री करा की सद्य चेकलिस्टमधील सर्व बाबी चिन्हांकित केल्या आहेत.",
    },
  };

  const InspectionChecklistQuestion = {
    firstImageData,
    secondImageData,
    thirdImageData,
    config,
  };
  export default InspectionChecklistQuestion;