const ShopMeasurementsFormQuestion = {
  id: "shop_measurements_form",
  title_mr: "सर्व शॉप मोजमाप",
  title_en: "All Shop Measurements",
  fields: [
    {
      id: "shop_shutter_size",
      question_mr: "शॉप शटर साइज काय आहे?",
      question_en: "What is the shop shutter size?",
      type: "measurement",
      subfields: [
        {
          id: "length",
          label_mr: "लांबी (फूट)",
          label_en: "Length (ft)",
          value: "10",
        },
        {
          id: "height",
          label_mr: "उंची (फूट)",
          label_en: "Height (ft)",
          value: "1",
        },
        {
          id: "total_sqft",
          label_mr: "एकूण चौरस फूट",
          label_en: "Total sq ft",
          value: "200",
        },
      ],
    },
    {
      id: "flooring_size",
      question_mr: "फ्लोरीगं साइज घेणे",
      question_en: "Flooring Size",
      type: "measurement",
      subfields: [
        {
          id: "length",
          label_mr: "लांबी (फूट)",
          label_en: "Length (ft)",
          value: "10",
        },
        {
          id: "height",
          label_mr: "उंची (फूट)",
          label_en: "Height (ft)",
          value: "1",
        },
        {
          id: "total_sqft",
          label_mr: "एकूण चौरस फूट",
          label_en: "Total sq ft",
          value: "200",
        },
      ],
    },
    {
      id: "otta",
      question_mr: "ओटा",
      question_en: "Platform",
      type: "measurement",
      subfields: [
        {
          id: "length",
          label_mr: "लांबी (फूट)",
          label_en: "Length (ft)",
          value: "10",
        },
        {
          id: "height",
          label_mr: "उंची (फूट)",
          label_en: "Height (ft)",
          value: "1",
        },
        {
          id: "total_sqft",
          label_mr: "एकूण चौरस फूट",
          label_en: "Total sq ft",
          value: "50",
        },
      ],
    },
    {
      id: "left_wall",
      question_mr: "डाव्या बाजूची भिंत",
      question_en: "Left Wall",
      type: "measurement",
      subfields: [
        {
          id: "length",
          label_mr: "लांबी (फूट)",
          label_en: "Length (ft)",
          value: "15",
        },
        {
          id: "height",
          label_mr: "उंची (फूट)",
          label_en: "Height (ft)",
          value: "9",
        },
        {
          id: "total_sqft",
          label_mr: "एकूण चौरस फूट",
          label_en: "Total sq ft",
          value: "135",
        },
      ],
    },
    {
      id: "right_wall",
      question_mr: "उजव्या बाजूची भिंत",
      question_en: "Right Wall",
      type: "measurement",
      subfields: [
        {
          id: "height",
          label_mr: "उंची (फूट)",
          label_en: "Height (ft)",
          value: "15",
        },
        {
          id: "length",
          label_mr: "लांबी (फूट)",
          label_en: "Length (ft)",
          value: "9",
        },
        {
          id: "total_sqft",
          label_mr: "एकूण चौरस फूट",
          label_en: "Total sq ft",
          value: "135",
        },
      ],
    },
    {
      id: "back_wall",
      question_mr: "पाठीमागील भिंत",
      question_en: "Back Wall",
      type: "measurement",
      subfields: [
        {
          id: "length",
          label_mr: "लांबी (फूट)",
          label_en: "Length (ft)",
          value: "15",
        },
        {
          id: "height",
          label_mr: "उंची (फूट)",
          label_en: "Height (ft)",
          value: "9",
        },
        {
          id: "total_sqft",
          label_mr: "एकूण चौरस फूट",
          label_en: "Total sq ft",
          value: "135",
        },
      ],
    },
    {
      id: "pop_size",
      question_mr: "शॉप POP साइज घेणे",
      question_en: "Shop POP Size",
      type: "measurement",
      subfields: [
        {
          id: "length",
          label_mr: "लांबी (फूट)",
          label_en: "Length (ft)",
          value: "10",
        },
        {
          id: "height",
          label_mr: "उंची (फूट)",
          label_en: "Height (ft)",
          value: "1",
        },
        {
          id: "total_sqft",
          label_mr: "एकूण चौरस फूट",
          label_en: "Total sq ft",
          value: "200",
        },
      ],
    },
    {
      id: "shop_ceiling",
      question_mr: "शॉप सीलिंग",
      question_en: "Shop Ceiling",
      type: "measurement",
      subfields: [
        {
          id: "length",
          label_mr: "लांबी (फूट)",
          label_en: "Length (ft)",
          value: "10",
        },
        {
          id: "height",
          label_mr: "उंची (फूट)",
          label_en: "Height (ft)",
          value: "1",
        },
        {
          id: "total_sqft",
          label_mr: "एकूण चौरस फूट",
          label_en: "Total sq ft",
          value: "200",
        },
      ],
    },
    {
      id: "shop_shutter",
      question_mr: "शॉप शटर",
      question_en: "Shop Shutter",
      type: "measurement",
      subfields: [
        {
          id: "length",
          label_mr: "लांबी (फूट)",
          label_en: "Length (ft)",
          value: "10",
        },
        {
          id: "height",
          label_mr: "उंची (फूट)",
          label_en: "Height (ft)",
          value: "1",
        },
        {
          id: "total_sqft",
          label_mr: "एकूण चौरस फूट",
          label_en: "Total sq ft",
          value: "200",
        },
      ],
    },
    {
      id: "extra_color_work",
      question_mr: "एक्स्ट्रा कलर वर्क",
      question_en: "Extra Color Work",
      type: "measurement",
      subfields: [
        {
          id: "length",
          label_mr: "लांबी (फूट)",
          label_en: "Length (ft)",
          value: "1",
        },
        {
          id: "height",
          label_mr: "उंची (फूट)",
          label_en: "Height (ft)",
          value: "1",
        },
        {
          id: "total_sqft",
          label_mr: "एकूण चौरस फूट",
          label_en: "Total sq ft",
          value: "1",
        },
      ],
    },
    {
      id: "main_board_letter_size",
      question_mr: "मेन बोर्ड लेटर साइज घेणे",
      question_en: "Main Board Letter Size",
      type: "measurement",
      subfields: [
        {
          id: "length",
          label_mr: "लांबी (फूट)",
          label_en: "Length (ft)",
          value: "10",
        },
        {
          id: "height",
          label_mr: "उंची (फूट)",
          label_en: "Height (ft)",
          value: "5",
        },
        {
          id: "total_sqft",
          label_mr: "एकूण चौरस फूट",
          label_en: "Total sq ft",
          value: "50",
        },
      ],
    },
    {
      id: "main_board_acp_panel",
      question_mr: "मेन बोर्ड ACP पॅनल साइझ (बोर्ड)",
      question_en: "Main Board ACP Panel Size (Board)",
      type: "measurement",
      subfields: [
        {
          id: "length",
          label_mr: "लांबी (फूट)",
          label_en: "Length (ft)",
          value: "5",
        },
        {
          id: "height",
          label_mr: "उंची (फूट)",
          label_en: "Height (ft)",
          value: "10",
        },
        {
          id: "total_sqft",
          label_mr: "एकूण चौरस फूट",
          label_en: "Total sq ft",
          value: "50",
        },
      ],
    },
    {
      id: "ceiling_details",
      question_mr: "सीलिंग तपशील",
      question_en: "Ceiling Details",
      type: "measurement",
      subfields: [
        {
          id: "length",
          label_mr: "लांबी (फूट)",
          label_en: "Length (ft)",
          value: "1",
        },
        {
          id: "height",
          label_mr: "उंची (फूट)",
          label_en: "Height (ft)",
          value: "1",
        },
        {
          id: "total_sqft",
          label_mr: "एकूण चौरस फूट",
          label_en: "Total sq ft",
          value: "1",
        },
      ],
    },
    {
      id: "top_side",
      question_mr: "वरची बाजू",
      question_en: "Top Side",
      type: "measurement",
      subfields: [
        {
          id: "length",
          label_mr: "लांबी (फूट)",
          label_en: "Length (ft)",
          value: "1",
        },
        {
          id: "height",
          label_mr: "उंची (फूट)",
          label_en: "Height (ft)",
          value: "1",
        },
        {
          id: "total_sqft",
          label_mr: "एकूण चौरस फूट",
          label_en: "Total sq ft",
          value: "1",
        },
      ],
    },
    {
      id: "left_right_sides",
      question_mr: "डावी आणि उजवी दोन्ही बाजू",
      question_en: "Left and Right Two Sides",
      type: "measurement",
      subfields: [
        {
          id: "length",
          label_mr: "लांबी (फूट)",
          label_en: "Length (ft)",
          value: "1",
        },
        {
          id: "height",
          label_mr: "उंची (फूट)",
          label_en: "Height (ft)",
          value: "1",
        },
        {
          id: "total_sqft",
          label_mr: "एकूण चौरस फूट",
          label_en: "Total sq ft",
          value: "1",
        },
      ],
    },
    {
      id: "canopy",
      question_mr: "कॅनोपी",
      question_en: "Canopy",
      type: "measurement",
      subfields: [
        {
          id: "length",
          label_mr: "लांबी (फूट)",
          label_en: "Length (ft)",
          value: "1",
        },
        {
          id: "height",
          label_mr: "उंची (फूट)",
          label_en: "Height (ft)",
          value: "1",
        },
        {
          id: "total_sqft",
          label_mr: "एकूण चौरस फूट",
          label_en: "Total sq ft",
          value: "1",
        },
      ],
    },
    {
      id: "back_side",
      question_mr: "मागची बाजू",
      question_en: "Back Side",
      type: "measurement",
      subfields: [
        {
          id: "length",
          label_mr: "लांबी (फूट)",
          label_en: "Length (ft)",
          value: "1",
        },
        {
          id: "height",
          label_mr: "उंची (फूट)",
          label_en: "Height (ft)",
          value: "1",
        },
        {
          id: "total_sqft",
          label_mr: "एकूण चौरस फूट",
          label_en: "Total sq ft",
          value: "1",
        },
      ],
    },
    {
      id: "shop_partition",
      question_mr: "शॉप पार्टिशन",
      question_en: "Shop Partition",
      type: "measurement",
      subfields: [
        {
          id: "length",
          label_mr: "लांबी (फूट)",
          label_en: "Length (ft)",
          value: "1",
        },
        {
          id: "height",
          label_mr: "उंची (फूट)",
          label_en: "Height (ft)",
          value: "1",
        },
        {
          id: "total_sqft",
          label_mr: "एकूण चौरस फूट",
          label_en: "Total sq ft",
          value: "1",
        },
      ],
    },
    {
      id: "potmala_partition",
      question_mr: "पोतमाला पार्टिशन",
      question_en: "Potmala Partition",
      type: "measurement",
      subfields: [
        {
          id: "length",
          label_mr: "लांबी (फूट)",
          label_en: "Length (ft)",
          value: "1",
        },
        {
          id: "height",
          label_mr: "उंची (फूट)",
          label_en: "Height (ft)",
          value: "1",
        },
        {
          id: "total_sqft",
          label_mr: "एकूण चौरस फूट",
          label_en: "Total sq ft",
          value: "1",
        },
      ],
    },
    {
      id: "other_partition",
      question_mr: "इतर पार्टिशन",
      question_en: "Other Partition",
      type: "measurement",
      subfields: [
        {
          id: "length",
          label_mr: "लांबी (फूट)",
          label_en: "Length (ft)",
          value: "1",
        },
        {
          id: "height",
          label_mr: "उंची (फूट)",
          label_en: "Height (ft)",
          value: "1",
        },
        {
          id: "total_sqft",
          label_mr: "एकूण चौरस फूट",
          label_en: "Total sq ft",
          value: "1",
        },
      ],
    },
    {
      id: "shutter_patta",
      question_mr: "शटर पट्टा",
      question_en: "Shutter Patta",
      type: "measurement",
      subfields: [
        {
          id: "length",
          label_mr: "लांबी (फूट)",
          label_en: "Length (ft)",
          value: "1",
        },
        {
          id: "height",
          label_mr: "उंची (फूट)",
          label_en: "Height (ft)",
          value: "1",
        },
        {
          id: "total_sqft",
          label_mr: "एकूण चौरस फूट",
          label_en: "Total sq ft",
          value: "1",
        },
      ],
    },
  ],
  submit_button_mr: "सबमिट करा",
  submit_button_en: "Submit",
  navigation_buttons: {
    back_mr: "मागे",
    back_en: "Back",
    next_mr: "पुढे",
    next_en: "Next",
  },
  submission_message_mr: `सर आपले खूप खूप धन्यवाद की आपण वरील पूर्ण माहिती आम्हाला दिली आहे. आम्ही तुम्हाला प्रोजेक्टसाठी लागणाऱ्या मटेरियलचे कोटेशन पुढील कामाच्या वेळेत 24 तासाच्या आत मध्ये पाठवू आणि त्यानंतर तुम्हाला वास्तविक कामाबद्दल पूर्ण माहिती दिली जाईल. इंजिनियर कडून. धन्यवाद.`,
  submission_message_en: `Thank you very much sir for providing us with all the above information. We will send you the material quotation required for the project within 24 hours of the next working time and after that you will be given complete information about the actual work. From Engineer. Thank you.`,
};

export default ShopMeasurementsFormQuestion;