
  const categories = [
    'A: Initial Items',
    'B: Electronic Appliances',
    'B+: Additional Electronic Appliances',
    'C: Kitchen Cutlery',
    'D: Housekeeping Material',
    'E: Stationery',
    'F: Display & Sign Board ACP',
    'F-2: Letter Name Board Work',
    'G: Other Expenses',
  ];

  // Assign categories to checklist items with corrected numbering
  const checklistData = [
    { category: 'A: Initial Items', no: 1, particulars_en: "Burner Bhatti", particulars_mr: "बर्नर भट्टी", size: "44*24*30+6", qty: 1, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
    { category: 'A: Initial Items', no: 2, particulars_en: "Service Counter", particulars_mr: "सर्व्हिस काउंटर", size: "72*24*30+14+12", qty: 1, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
    { category: 'A: Initial Items', no: 3, particulars_en: "Single Sink Big", particulars_mr: "सिंगल सिंक मोठा", size: "24*24*30+18+12", qty: 1, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
    { category: 'A: Initial Items', no: 4, particulars_en: "Work Table", particulars_mr: "वर्क टेबल", size: "36*20*30+18+12", qty: 1, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
    { category: 'A: Initial Items', no: 5, particulars_en: "Side Table", particulars_mr: "साइड टेबल", size: "32*24*30+18+12", qty: 2, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
    { category: 'A: Initial Items', no: 6, particulars_en: "Fridge 500 Ltr (Blue Star)", particulars_mr: "फ्रिज 500 लिटर (ब्लू स्टार)", size: "66*28*30", qty: 1, defaultAvailability: "no", remarks_en: "1 Year Compressor (Manufacturer)", remarks_mr: "1 वर्ष कंप्रेसर (निर्माता)" },
    { category: 'A: Initial Items', no: 7, particulars_en: "Idli Steamer", particulars_mr: "इडली स्टीमर", size: "42*36*45", qty: 1, defaultAvailability: "no", remarks_en: "Only Boiler 6 Months (Manufacturer)", remarks_mr: "फक्त बॉयलर 6 महिने (निर्माता)" },
    { category: 'A: Initial Items', no: 8, particulars_en: "Round Table", particulars_mr: "गोल टेबल", size: "30x30x48", qty: 4, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
    { category: 'A: Initial Items', no: 9, particulars_en: "Thatte Idli SS Non-Stick Tray", particulars_mr: "थट्टे इडली स्टेनलेस स्टील नॉन-स्टिक ट्रे", size: "", qty: 2, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
    { category: 'A: Initial Items', no: 10, particulars_en: "Button Idli SS Non-Stick Tray", particulars_mr: "बटण इडली स्टेनलेस स्टील नॉन-स्टिक ट्रे", size: "", qty: 2, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
    { category: 'A: Initial Items', no: 11, particulars_en: "KOT Bill", particulars_mr: "KOT बिल", size: "18", qty: 1, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
    { category: 'A: Initial Items', no: 12, particulars_en: "Fryer Kit Details / Medu Vada", particulars_mr: "फ्रायर किट / मेदू वडा", size: "8 Pieces Fryer Kit", qty: 1, defaultAvailability: "no", remarks_en: "1 Year Manufacturer", remarks_mr: "1 वर्ष निर्माता" },
    { category: 'B: Electronic Appliances', no: 1, particulars_en: "Bill Machine", particulars_mr: "बिल मशीन", size: "Caption POS 15.6 Inch", qty: 1, defaultAvailability: "yes", remarks_en: "1 Year Manufacturer", remarks_mr: "1 वर्ष निर्माता" },
    { category: 'B: Electronic Appliances', no: 2, particulars_en: "Thermal Printer", particulars_mr: "थर्मल प्रिंटर", size: "Caption POS 2 Inch", qty: 1, defaultAvailability: "yes", remarks_en: "1 Year Manufacturer", remarks_mr: "1 वर्ष निर्माता" },
    { category: 'B: Electronic Appliances', no: 3, particulars_en: "Software", particulars_mr: "सॉफ्टवेअर", size: "PetPuja", qty: 1, defaultAvailability: "yes", remarks_en: "1 Year Manufacturer", remarks_mr: "1 वर्ष निर्माता" },
    { category: 'B+: Additional Electronic Appliances', no: 1, particulars_en: "Coffee Machine", particulars_mr: "कॉफी मशीन", size: "", qty: 1, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
    { category: 'B+: Additional Electronic Appliances', no: 2, particulars_en: "MS Dustbin Table", particulars_mr: "एमएस डस्टबिन टेबल", size: "20x20x16", qty: 1, defaultAvailability: "yes", remarks_en: "1 Year Manufacturer", remarks_mr: "1 वर्ष निर्माता" },
    { category: 'B+: Additional Electronic Appliances', no: 3, particulars_en: "Store Rack", particulars_mr: "स्टोअर रॅक", size: "36*18*6 Galvanised", qty: 1, defaultAvailability: "yes", remarks_en: "1 Year Manufacturer", remarks_mr: "1 वर्ष निर्माता" },
    { category: 'C: Kitchen Cutlery', no: 1, particulars_en: "Fire Tank", particulars_mr: "फायर टँक", size: "Refill Installation 1 Year - 6KG", qty: 1, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
    { category: 'C: Kitchen Cutlery', no: 2, particulars_en: "Cutlery Material Kit Set 8 Nos", particulars_mr: "कटलरी मटेरियल किट सेट 8 नग", size: "Mini Idli, Fry Bottle, Front Scoop, Stainless Steel Spatula, Silicone Brush, 12 No. SS Mug with Plate, Spice Bottle, Tong, 100 Idli Scoop", qty: 1, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
    { category: 'C: Kitchen Cutlery', no: 3, particulars_en: "Plates", particulars_mr: "प्लेट्स", size: "10*5, Bowl-3", qty: 70, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
    { category: 'C: Kitchen Cutlery', no: 4, particulars_en: "Spoon and Fork", particulars_mr: "चमचा आणि काटा", size: "100 Pcs", qty: 75, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
    { category: 'C: Kitchen Cutlery', no: 5, particulars_en: "Spoon", particulars_mr: "चमचा", size: "100 Pcs", qty: 125, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
    { category: 'C: Kitchen Cutlery', no: 6, particulars_en: "Aluminium Patila", particulars_mr: "अ‍ॅल्युमिनियम पातेला", size: "3 Piece Set 32, 28, 21", qty: 1, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
    { category: 'C: Kitchen Cutlery', no: 7, particulars_en: "Cutting Gattu", particulars_mr: "कटिंग गट्टू", size: "12*3", qty: 1, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
    { category: 'C: Kitchen Cutlery', no: 8, particulars_en: "Chopping Pad", particulars_mr: "चॉपिंग पॅड", size: "", qty: 1, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
    { category: 'C: Kitchen Cutlery', no: 9, particulars_en: "Bill Tochya", particulars_mr: "बिल तोच्या", size: "Height-18", qty: 1, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
    { category: 'C: Kitchen Cutlery', no: 10, particulars_en: "Chaku SS Material", particulars_mr: "चाकू स्टेनलेस स्टील मटेरियल", size: "13*3 mm", qty: 1, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
    { category: 'C: Kitchen Cutlery', no: 11, particulars_en: "Tea Patila", particulars_mr: "चहा पातेला", size: "4 Ltr - With Kalai", qty: 1, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
    { category: 'C: Kitchen Cutlery', no: 12, particulars_en: "Print Roll", particulars_mr: "प्रिंट रोल", size: "27*13 Mtr", qty: 200, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
    { category: 'C: Kitchen Cutlery', no: 13, particulars_en: "Acrylic Single Oval Dish", particulars_mr: "अ‍ॅक्रिलिक सिंगल ओव्हल डिश", size: "Bowl Plate Small", qty: 100, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
    { category: 'C: Kitchen Cutlery', no: 14, particulars_en: "MS Chaku", particulars_mr: "एमएस चाकू", size: "12*2.5", qty: 2, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
    { category: 'C: Kitchen Cutlery', no: 15, particulars_en: "Tea VARGALE", particulars_mr: "चहा वर्गले", size: "", qty: 1, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
    { category: 'C: Kitchen Cutlery', no: 16, particulars_en: "SS Gang with Lid", particulars_mr: "स्टेनलेस स्टील गंग झाकणासह", size: "7 Liter", qty: 1, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
    { category: 'C: Kitchen Cutlery', no: 17, particulars_en: "SS Gang with Lid", particulars_mr: "स्टेनलेस स्टील गंग झाकणासह", size: "5 Liter", qty: 2, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },

    {
    "category": "C: Kitchen Cutlery",
    "no": 18,
    "particulars_en": "Tea Galan",
    "particulars_mr": "स्टील टी गालन (मोठा)",
    "size": "Steel Material Big",
    "qty": 1,
    "defaultAvailability": "yes",
    "remarks_en": "Checking Warranty",
    "remarks_mr": "वॉरंटी तपासणी"
  },
  {
    "category": "C: Kitchen Cutlery",
    "no": 19,
    "particulars_en": "Plastic Masala Dabi",
    "particulars_mr": "प्लास्टिक मसाला डबी",
    "size": "3 Ltr",
    "qty": 1,
    "defaultAvailability": "yes",
    "remarks_en": "Checking Warranty",
    "remarks_mr": "वॉरंटी तपासणी"
  },
  {
    "category": "C: Kitchen Cutlery",
    "no": 20,
    "particulars_en": "Plastic Masala Dabi",
    "particulars_mr": "प्लास्टिक मसाला डबी",
    "size": "1 Ltr",
    "qty": 6,
    "defaultAvailability": "yes",
    "remarks_en": "Checking Warranty",
    "remarks_mr": "वॉरंटी तपासणी"
  },
  {
    "category": "C: Kitchen Cutlery",
    "no": 21,
    "particulars_en": "Small Zarya",
    "particulars_mr": "छोटे जरिया (हेवी सपोर्ट)",
    "size": "Heavy Sopport",
    "qty": 1,
    "defaultAvailability": "yes",
    "remarks_en": "Checking Warranty",
    "remarks_mr": "वॉरंटी तपासणी"
  },
  {
    "category": "C: Kitchen Cutlery",
    "no": 22,
    "particulars_en": "Stone-Pakkad",
    "particulars_mr": "स्टोन पकड (एमएस मटेरियल)",
    "size": "Ms Material",
    "qty": 1,
    "defaultAvailability": "yes",
    "remarks_en": "Checking Warranty",
    "remarks_mr": "वॉरंटी तपासणी"
  },
  {
    "category": "C: Kitchen Cutlery",
    "no": 23,
    "particulars_en": "Idali Pali Ss",
    "particulars_mr": "इडली पळी स्टेनलेस स्टील",
    "size": "30 Ml",
    "qty": 1,
    "defaultAvailability": "yes",
    "remarks_en": "Checking Warranty",
    "remarks_mr": "वॉरंटी तपासणी"
  },
  {
    "category": "C: Kitchen Cutlery",
    "no": 24,
    "particulars_en": "Chatni Pali Ss",
    "particulars_mr": "चटणी पळी स्टेनलेस स्टील",
    "size": "100 Ml",
    "qty": 1,
    "defaultAvailability": "yes",
    "remarks_en": "Checking Warranty",
    "remarks_mr": "वॉरंटी तपासणी"
  },
  {
    "category": "C: Kitchen Cutlery",
    "no": 25,
    "particulars_en": "Rolli With Plate Ss",
    "particulars_mr": "प्लेटसह रोल्ली स्टील",
    "size": "Small",
    "qty": 1,
    "defaultAvailability": "yes",
    "remarks_en": "Checking Warranty",
    "remarks_mr": "वॉरंटी तपासणी"
  },
  {
    "category": "C: Kitchen Cutlery",
    "no": 26,
    "particulars_en": "Sambar Pali",
    "particulars_mr": "सांबार पळी",
    "size": "150ml",
    "qty": 1,
    "defaultAvailability": "yes",
    "remarks_en": "Checking Warranty",
    "remarks_mr": "वॉरंटी तपासणी"
  },
  {
    "category": "C: Kitchen Cutlery",
    "no": 27,
    "particulars_en": "Sambar Vargale",
    "particulars_mr": "सांबार वर्गाळे (अ‍ॅल्युमिनियम)",
    "size": "Aluminium Material 2ltr",
    "qty": 1,
    "defaultAvailability": "yes",
    "remarks_en": "Checking Warranty",
    "remarks_mr": "वॉरंटी तपासणी"
  },
  {
    "category": "C: Kitchen Cutlery",
    "no": 28,
    "particulars_en": "Lighter",
    "particulars_mr": "लाईटर",
    "size": "18",
    "qty": 2,
    "defaultAvailability": "yes",
    "remarks_en": "Checking Warranty",
    "remarks_mr": "वॉरंटी तपासणी"
  },
  {
    "category": "C: Kitchen Cutlery",
    "no": 29,
    "particulars_en": "Magnet Stick",
    "particulars_mr": "मॅग्नेट स्टिक",
    "size": "",
    "qty": 1,
    "defaultAvailability": "yes",
    "remarks_en": "Checking Warranty",
    "remarks_mr": "वॉरंटी तपासणी"
  },
  {
    "category": "C: Kitchen Cutlery",
    "no": 30,
    "particulars_en": "Coockware",
    "particulars_mr": "कूकवेअर (१४ लिटर, ३.५ किग्रॅ क्षमता)",
    "size": "14liter - 3.5kg Capacity",
    "qty": 1,
    "defaultAvailability": "yes",
    "remarks_en": "Checking Warranty",
    "remarks_mr": "वॉरंटी तपासणी"
  },
  {
    "category": "C: Kitchen Cutlery",
    "no": 31,
    "particulars_en": "Tharmas 3 Ltr",
    "particulars_mr": "थरमस ३ लिटर (मिल्टोन १ वर्षांची वॉरंटी)",
    "size": "Miltone Company 1 Years",
    "qty": 1,
    "defaultAvailability": "yes",
    "remarks_en": "1 year mfg company",
    "remarks_mr": "१ वर्ष निर्मात्याची वॉरंटी"
  },
  {
    "category": "C: Kitchen Cutlery",
    "no": 32,
    "particulars_en": "Mixter",
    "particulars_mr": "मिक्सर (RPM 27000 ते 28000)",
    "size": "27000 To 28000 Rpm",
    "qty": 1,
    "defaultAvailability": "yes",
    "remarks_en": "Checking Warranty",
    "remarks_mr": "वॉरंटी तपासणी"
  },
  {
    "category": "C: Kitchen Cutlery",
    "no": 33,
    "particulars_en": "Vajan Kata",
    "particulars_mr": "वजन काटा (५ किग्रॅ क्षमता, स्थानिक)",
    "size": "5 Kg Capacity Local",
    "qty": 1,
    "defaultAvailability": "yes",
    "remarks_en": "Checking Warranty",
    "remarks_mr": "वॉरंटी तपासणी"
  },
  {
    "category": "C: Kitchen Cutlery",
    "no": 34,
    "particulars_en": "Hot Case",
    "particulars_mr": "हॉट केस",
    "size": "Hotcase",
    "qty": 1,
    "defaultAvailability": "yes",
    "remarks_en": "Checking Warranty",
    "remarks_mr": "वॉरंटी तपासणी"
  },

    { category: 'D: Housekeeping Material', no: 1, particulars_en: "Uniform T-Shirt", particulars_mr: "युनिफॉर्म टी-शर्ट", size: "Labour-6", qty: 12, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
    { category: 'D: Housekeeping Material', no: 2, particulars_en: "Apron", particulars_mr: "एप्रन", size: "As Per Branding NB All Staff", qty: 12, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
    { category: 'D: Housekeeping Material', no: 3, particulars_en: "Cap", particulars_mr: "टोपी", size: "As Per Branding NB All Staff", qty: 12, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
    { category: 'D: Housekeeping Material', no: 4, particulars_en: "Paper Cup 65 ml", particulars_mr: "पेपर कप 65 मिली", size: "5000 Pcs", qty: 1, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
    { category: 'D: Housekeeping Material', no: 5, particulars_en: "Paper Cup 85 ml", particulars_mr: "पेपर कप 85 मिली", size: "5000 Pcs", qty: 1, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
    { category: 'D: Housekeeping Material', no: 6, particulars_en: "Dustbin Swing", particulars_mr: "डस्टबिन स्विंग", size: "Yellow 60 / Pavan/Nakoda", qty: 2, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
    { category: 'D: Housekeeping Material', no: 7, particulars_en: "Dustbin Small", particulars_mr: "डस्टबिन छोटा", size: "30 Ltr Nakoda Square/Pavan", qty: 1, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
    { category: 'D: Housekeeping Material', no: 8, particulars_en: "Queue Manager", particulars_mr: "क्यू मॅनेजर", size: "", qty: 2, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
    { category: 'D: Housekeeping Material', no: 9, particulars_en: "Floor Cleaner", particulars_mr: "फ्लोअर क्लिनर", size: "5 Ltr", qty: 1, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
    { category: 'D: Housekeeping Material', no: 10, particulars_en: "Floor Duster", particulars_mr: "फ्लोअर डस्टर", size: "", qty: 6, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
    { category: 'D: Housekeeping Material', no: 11, particulars_en: "Check Duster", particulars_mr: "चेक डस्टर", size: "", qty: 6, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
    { category: 'D: Housekeeping Material', no: 12, particulars_en: "Cello Mop", particulars_mr: "सेलो मॉप", size: "", qty: 1, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
    { category: 'D: Housekeeping Material', no: 13, particulars_en: "Broom", particulars_mr: "झाडू", size: "Gala Plastic Broom XL", qty: 1, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
    { category: 'D: Housekeeping Material', no: 14, particulars_en: "Green Scrubber", particulars_mr: "हिरवी घासणी", size: "", qty: 10, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
   
    { "category": "D: Housekeeping Material", "no": 15, "particulars_en": "Stool", "particulars_mr": "स्टूल", "size": "", "qty": 4, "defaultAvailability": "yes", "remarks_en": "Checking Warranty", "remarks_mr": "वॉरंटी तपासणी" },
  { "category": "D: Housekeeping Material", "no": 16, "particulars_en": "Plastic Mug", "particulars_mr": "प्लास्टिक मग", "size": "Marking - 1500ml White", "qty": 1, "defaultAvailability": "yes", "remarks_en": "Checking Warranty", "remarks_mr": "वॉरंटी तपासणी" },
  { "category": "D: Housekeeping Material", "no": 17, "particulars_en": "Plastic Water Jar", "particulars_mr": "प्लास्टिक पाणी जार", "size": "Marking 20 Liter White", "qty": 2, "defaultAvailability": "yes", "remarks_en": "Checking Warranty", "remarks_mr": "वॉरंटी तपासणी" },
  { "category": "D: Housekeeping Material", "no": 18, "particulars_en": "Plastic Water Jar", "particulars_mr": "प्लास्टिक पाणी जार", "size": "Marking - 9 Liter White", "qty": 1, "defaultAvailability": "yes", "remarks_en": "Checking Warranty", "remarks_mr": "वॉरंटी तपासणी" },
  { "category": "D: Housekeeping Material", "no": 19, "particulars_en": "Handwash", "particulars_mr": "हँडवॉश", "size": "5 Ltr", "qty": 1, "defaultAvailability": "yes", "remarks_en": "Checking Warranty", "remarks_mr": "वॉरंटी तपासणी" },
  { "category": "D: Housekeeping Material", "no": 20, "particulars_en": "Dishwash", "particulars_mr": "डिशवॉश", "size": "5 Ltr", "qty": 1, "defaultAvailability": "yes", "remarks_en": "Checking Warranty", "remarks_mr": "वॉरंटी तपासणी" },
  { "category": "D: Housekeeping Material", "no": 21, "particulars_en": "Plastic Bottle", "particulars_mr": "प्लास्टिक बाटली", "size": "1 Ltr - Black", "qty": 6, "defaultAvailability": "yes", "remarks_en": "Checking Warranty", "remarks_mr": "वॉरंटी तपासणी" },
  { "category": "D: Housekeeping Material", "no": 22, "particulars_en": "Plate Cleaning Kapad", "particulars_mr": "प्लेट स्वच्छतेसाठी कपडा", "size": "1*1 - Smooth", "qty": 12, "defaultAvailability": "yes", "remarks_en": "Checking Warranty", "remarks_mr": "वॉरंटी तपासणी" },
  { "category": "D: Housekeeping Material", "no": 23, "particulars_en": "Wiper", "particulars_mr": "वायपर", "size": "For Tiles Clean 16\"", "qty": 1, "defaultAvailability": "yes", "remarks_en": "Checking Warranty", "remarks_mr": "वॉरंटी तपासणी" },
  { "category": "D: Housekeeping Material", "no": 24, "particulars_en": "Small Wiper", "particulars_mr": "छोटा वायपर", "size": "For Steamer", "qty": 2, "defaultAvailability": "yes", "remarks_en": "Checking Warranty", "remarks_mr": "वॉरंटी तपासणी" },
  { "category": "D: Housekeeping Material", "no": 25, "particulars_en": "Timer Machine", "particulars_mr": "टायमर मशीन", "size": "", "qty": 3, "defaultAvailability": "yes", "remarks_en": "Checking Warranty", "remarks_mr": "वॉरंटी तपासणी" },
  { "category": "D: Housekeeping Material", "no": 26, "particulars_en": "Hand Glove", "particulars_mr": "हातमोजे", "size": "", "qty": 10, "defaultAvailability": "yes", "remarks_en": "Checking Warranty", "remarks_mr": "वॉरंटी तपासणी" },
  { "category": "D: Housekeeping Material", "no": 27, "particulars_en": "Dustbin Black", "particulars_mr": "ब्लॅक डस्टबिन", "size": "", "qty": 1, "defaultAvailability": "yes", "remarks_en": "Checking Warranty", "remarks_mr": "वॉरंटी तपासणी" },
   
   
   
    { category: 'E: Stationery', no: 1, particulars_en: "Scissors", particulars_mr: "कात्री", size: "", qty: 1, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
    { category: 'E: Stationery', no: 2, particulars_en: "NB Pen", particulars_mr: "एनबी पेन", size: "", qty: 50, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
    { category: 'E: Stationery', no: 3, particulars_en: "Two-Way Cello Tape", particulars_mr: "द्विमार्गी सेलो टेप", size: "", qty: 2, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
    { category: 'E: Stationery', no: 4, particulars_en: "Ribbon Opening-Flower", particulars_mr: "रिबन ओपनिंग-फूल", size: "", qty: 1, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
    { category: 'E: Stationery', no: 5, particulars_en: "Kitchen NB", particulars_mr: "किचन एनबी", size: "", qty: 50, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
    { category: 'E: Stationery', no: 6, particulars_en: "Laminated Sticker", particulars_mr: "लॅमिनेटेड स्टिकर", size: "", qty: 10, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
    { category: 'E: Stationery', no: 7, particulars_en: "Notebook", particulars_mr: "नोटबुक", size: "", qty: 2, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
    { category: 'E: Stationery', no: 8, particulars_en: "First Aid Kit", particulars_mr: "प्रथमोपचार किट", size: "", qty: 1, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
    { category: 'E: Stationery', no: 9, particulars_en: "Presenty Register", particulars_mr: "उपस्थिती रजिस्टर", size: "", qty: 1, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
    { category: 'E: Stationery', no: 10, particulars_en: "Calculator", particulars_mr: "कॅल्क्युलेटर", size: "", qty: 1, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
    { category: 'E: Stationery', no: 11, particulars_en: "Cello Tape Cutter", particulars_mr: "सेलो टेप कटर", size: "", qty: 1, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
    { category: 'E: Stationery', no: 12, particulars_en: "Rubber Packet", particulars_mr: "रबर पॅकेट", size: "", qty: 1, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
    { category: 'E: Stationery', no: 13, particulars_en: "Tissue Paper Box", particulars_mr: "टिश्यू पेपर बॉक्स", size: "", qty: 1, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
    { category: 'E: Stationery', no: 14, particulars_en: "Cello Tape", particulars_mr: "सेलो टेप", size: "1 Inch x 6 Pc Packet", qty: 1, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
    { category: 'E: Stationery', no: 15, particulars_en: "Long Book", particulars_mr: "लांब बुक", size: "", qty: 1, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
    { category: 'E: Stationery', no: 16, particulars_en: "Pen Drive", particulars_mr: "पेन ड्राइव्ह", size: "", qty: 1, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
    { category: 'F: Display & Sign Board ACP', no: 1, particulars_en: "Main Board + Shop Partition - ACP", particulars_mr: "मुख्य बोर्ड + शॉप पार्टीशन - एसीपी", size: "3mm ACP Sheet", qty: 470, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
    { category: 'F: Display & Sign Board ACP', no: 2, particulars_en: "Fabrication for Board & Partition", particulars_mr: "बोर्ड आणि पार्टीशनसाठी फॅब्रिकेशन", size: "1.5mm Square MS Pipe", qty: 355, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
    { category: 'F: Display & Sign Board ACP', no: 3, particulars_en: "Gas Bank", particulars_mr: "गॅस बँक", size: "20x36x32", qty: 1, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
    { category: 'F-2: Letter Name Board Work', no: 1, particulars_en: "Photo Frame 4 Pieces", particulars_mr: "फोटो फ्रेम 4 नग", size: "3mm Acrylic & LED", qty: 4, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
    { category: 'F-2: Letter Name Board Work', no: 2, particulars_en: "Vinyl Sticker + Foam Sheet", particulars_mr: "विनाइल स्टिकर + फोम शीट", size: "", qty: 1, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
    { category: 'F-2: Letter Name Board Work', no: 3, particulars_en: "Letter Work (Marathi)", particulars_mr: "लेटर वर्क (मराठी)", size: "2 & 3 mm Acrylic Sheet, LED", qty: 379, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
    { category: 'F-2: Letter Name Board Work', no: 4, particulars_en: "Letter / Board Scrap Hoarding", particulars_mr: "लेटर / बोर्ड स्क्रॅप होर्डिंग", size: "Board / Letter All Material", qty: 1, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
    { category: 'F-2: Letter Name Board Work', no: 5, particulars_en: "Lollipop", particulars_mr: "लॉलीपॉप", size: "3mm Acrylic & LED", qty: 1, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
    { category: 'G: Other Expenses', no: 1, particulars_en: "Steamer Installation Charges", particulars_mr: "स्टीमर स्थापना शुल्क", size: "Transport + Labour + Material", qty: 1, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
    { category: 'G: Other Expenses', no: 2, particulars_en: "Agreement Fee", particulars_mr: "करार शुल्क", size: "Stamp + Draft + Notary", qty: 1, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
    { category: 'G: Other Expenses', no: 3, particulars_en: "Drawing Fee", particulars_mr: "ड्रॉइंग शुल्क", size: "All Civil + Code + Photo", qty: 1, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
    { category: 'G: Other Expenses', no: 4, particulars_en: "Transport Setup Material All", particulars_mr: "सर्व सेटअप मटेरियल वाहतूक", size: "Pune to Your Shop", qty: 1, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
    { category: 'G: Other Expenses', no: 5, particulars_en: "Visit Fee - Owner On-Site Dinner", particulars_mr: "भेट शुल्क - मालक ऑन-साइट डिनर", size: "Plan + Checking + Setup + Opening", qty: 3, defaultAvailability: "yes", remarks_en: "Checking Warranty", remarks_mr: "वॉरंटी तपासणी" },
  ];

  const config = {
    en: {
      title: "Nadbrahma Idli Material List",
      branchName: "Branch Name: A.B. Road, Indore",
      ownerName: "Owner Name: Mr. Raj Anil Sisodiya",
      dateLabel: `Date: ${new Date().toLocaleDateString('en-GB')}`,
      mobileLabel: "Mobile Number: 9133128816",
      tableHeaders: [
        "No",
        "Particulars",
        "Size",
        "Qty",
        "Material Available",
        "Material Not Available",
        "Reason for Material Not Available",
      ],
      availabilityYes: "Yes",
      availabilityNo: "No",
      question: "Do you understand the above material checklist?",
      yes: "Yes",
      no: "No",
      submit: "Submit",
      back: "Back",
      next: "Next",
      availabilityError: "Please select availability for all materials.",
      agreementError: "Please select whether you understand the material checklist.",
      successMessage: "Form submitted successfully!",
      errorMessage: "Error submitting form!",
    },
    mr: {
      title: "नादब्रह्मा इडली मटेरियल यादी",
      branchName: "शाखेचे नाव: ए.बी. रोड, इंदूर",
      ownerName: "मालकाचे नाव: श्री. राज अनिल सिसोदिया",
      dateLabel: `तारीख: ${new Date().toLocaleDateString('en-GB')}`,
      mobileLabel: "मोबाइल क्रमांक: ९१३३१२८८१६",
      tableHeaders: [
        "अनु. क्र.",
        "विशेष",
        "आकार",
        "प्रमाण",
        "मटेरियल उपलब्ध",
        "मटेरियल अनुपलब्ध",
        "मटेरियल अनुपलब्ध असण्याचे कारण",
      ],
      availabilityYes: "होय",
      availabilityNo: "नाही",
      question: "तुम्हाला वरील मटेरियल यादी समजली का?",
      yes: "होय",
      no: "नाही",
      submit: "सबमिट",
      back: "मागे",
      next: "पुढे",
      availabilityError: "कृपया सर्व मटेरियल्ससाठी उपलब्धता निवडा.",
      agreementError: "कृपया वरील मटेरियल यादी समजली आहे का याचे उत्तर निवडा.",
      successMessage: "फॉर्म यशस्वीरित्या सबमिट झाला!",
      errorMessage: "फॉर्म सबमिट करण्यात त्रुटी!",
    },
  };

const MaterialCheckListQuestion = {
 categories,
 checklistData,
 config
};

export default MaterialCheckListQuestion;